name 'setup_swap'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures setup_swap'
long_description 'Installs/Configures setup_swap'
version '0.1.0'
